// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6cd8rwvJNw2BSpYkgzt1ht_GV4ekANM',
    appId: '1:322510306038:web:657ea35711e56eee098ad7',
    messagingSenderId: '322510306038',
    projectId: 'mobileappdev-513ed',
    authDomain: 'mobileappdev-513ed.firebaseapp.com',
    storageBucket: 'mobileappdev-513ed.appspot.com',
    measurementId: 'G-55CGVXH63W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN-BQithbGLlUM8yYMNCQxgPR09iE8d2A',
    appId: '1:322510306038:android:b174557bbfd2ec88098ad7',
    messagingSenderId: '322510306038',
    projectId: 'mobileappdev-513ed',
    storageBucket: 'mobileappdev-513ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOjIdb3sHi_wH-B6rrx5KlKhGlzNDNJHM',
    appId: '1:322510306038:ios:eaa4953935567858098ad7',
    messagingSenderId: '322510306038',
    projectId: 'mobileappdev-513ed',
    storageBucket: 'mobileappdev-513ed.appspot.com',
    iosBundleId: 'com.example.mobileAppDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOjIdb3sHi_wH-B6rrx5KlKhGlzNDNJHM',
    appId: '1:322510306038:ios:eaa4953935567858098ad7',
    messagingSenderId: '322510306038',
    projectId: 'mobileappdev-513ed',
    storageBucket: 'mobileappdev-513ed.appspot.com',
    iosBundleId: 'com.example.mobileAppDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP6cd8rwvJNw2BSpYkgzt1ht_GV4ekANM',
    appId: '1:322510306038:web:796bc3061f22da0a098ad7',
    messagingSenderId: '322510306038',
    projectId: 'mobileappdev-513ed',
    authDomain: 'mobileappdev-513ed.firebaseapp.com',
    storageBucket: 'mobileappdev-513ed.appspot.com',
    measurementId: 'G-701VG6XEQS',
  );
}
